### ISSUE TITLE
plans to support >8.0?

### ISSUE THREAD

**Issue by njm2112** [Acidham/alfred-search-1password#2]
1Password is now publicly testing v8.8, which should be released as the official version soon. Is there any plan to update this workflow to work with 1Password v8.8?

**Comment by Acidham** [comment]
No, because there is a more official version available: https://github.com/alfredapp/1password-workflow#readme

In addition, 1Password 8 comes with the own solution to Quick Access Passwords beyond what Alfred 1Password can provide: https://support.1password.com/quick-access/
